### PR TITLE
Fix requests version

### PR DESCRIPTION
**Pull request by anukul**

### CODE REVIEW

**Comment by wilzbach** [comment]
Maybe exclude v3?

**Comment by anukul** [comment]
CLI is broken due to this, just fixing that

**Comment by anukul** [comment]
@wilzbach Actually can you merge this please? I'm seeing an error while running the CLI locally for development.
```
$ story apps list
Traceback (most recent call last):
  File "/Users/anukul/.virtualenvs/cli/lib/python3.7/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/Users/anukul/.virtualenvs/cli/lib/python3.7/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/Users/anukul/.virtualenvs/cli/lib/python3.7/site-packages/pkg_resources/__init__.py", line 791, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (requests 2.22.0 (/Users/anukul/.virtualenvs/cli/lib/python3.7/site-packages/requests-2.22.0-py3.7.egg), Requirement.parse('requests==2.21.0'), {'story-hub'})```

**Comment by wilzbach** [comment]
You still need to exclude requests 3.

**Comment by wilzbach** [comment]
Superseded by https://github.com/storyscript/hub-sdk-python/pull/16

**Pull request closed without merging**
